name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci] format"
          branch: main
          commit_user_name: formatbot
          commit_user_email: bot@noreply.github.com
          commit_author: "formatbot <bot@noreply.github.com>"
